### ISSUE TITLE
LICENSE needs to be filled

### ISSUE THREAD

**Issue by parmentelat** [Sm00thix/IKPLS#12]
this line here

```
   Copyright [yyyy] [name of copyright owner]
```

is supposed to be filled

**Comment by parmentelat** [comment]
and oops I forgot to link the meta-issue
https://github.com/openjournals/joss-reviews/issues/6533

**Comment by Sm00thix** [comment]
Thank you. I will fill them out.

**Comment by Sm00thix** [comment]
The changes have been merged to the main branch. I will close this issue.
