### ISSUE TITLE
tests failing 

### ISSUE THREAD

**Issue by parmentelat** [Sm00thix/IKPLS#17]
<details>
<summary>
with my repo on 4762f65 I am experiencing one test failure; open to see details
</summary>

pytest
=========================================================================== test session starts ============================================================================
platform darwin -- Python 3.12.3, pytest-8.1.1, pluggy-1.4.0
rootdir: /private/tmp/IKPLS
configfile: pyproject.toml
collected 26 items

tests/test_ikpls.py ..........F...............                                [100%]

===================================== FAILURES ======================================
___________________________ TestClass.test_gradient_pls_1 ___________________________

self = <tests.test_ikpls.TestClass object at 0x156a850d0>

    def test_gradient_pls_1(self):
        """
        Description
        -----------
        This test loads input predictor variables and a target variable with a single
        column and calls the 'check_gradient_pls' method to validate the gradient
        propagation for reverse-mode differentiable JAX PLS.

        Returns:
        None
        """
        X = self.load_X()
        Y = self.load_Y(["Protein"])
        num_components = 25
        filter_size = 7
        assert Y.shape[1] == 1
>       self.check_gradient_pls(
            X=X,
            Y=Y,
            num_components=num_components,
            filter_size=filter_size,
            val_atol=0,
            val_rtol=1e-5,
            grad_atol=0,
            grad_rtol=1e-5,
        )

tests/test_ikpls.py:2191:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_ikpls.py:2173: in check_gradient_pls
    assert_allclose(output_val_alg_2, output_val_diff_alg_2, atol=0, rtol=2e-11)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_allclose.<locals>.compare at 0x15a5949a0>, array(12.5455451), array(12.5455451))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=2e-11, atol=0', 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError:
E           Not equal to tolerance rtol=2e-11, atol=0
E
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 3.54010155e-10
E           Max relative difference: 2.8217997e-11
E            x: array(12.545545)
E            y: array(12.545545)

/Users/tparment/miniconda3/envs/my-ikpls/lib/python3.12/contextlib.py:81: AssertionError
------------------------------- Captured stdout call --------------------------------
stateless_fit for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_preprocess_input_matrices for Improved Kernel PLS Algorithm #1 will be JIT compiled...
get_means for Improved Kernel PLS Algorithm #1 will be JIT compiled...
get_stds for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_get_initial_matrices for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_1 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_main_loop_body for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_2 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_3 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_3_body for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_4 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_5 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
stateless_predict for Improved Kernel PLS Algorithm #1 will be JIT compiled...
stateless_fit for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_preprocess_input_matrices for Improved Kernel PLS Algorithm #2 will be JIT compiled...
get_means for Improved Kernel PLS Algorithm #2 will be JIT compiled...
get_stds for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_get_initial_matrices for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_1 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_main_loop_body for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_2 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_3 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_3_body for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_4 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_5 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
stateless_predict for Improved Kernel PLS Algorithm #2 will be JIT compiled...
stateless_fit for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_preprocess_input_matrices for Improved Kernel PLS Algorithm #1 will be JIT compiled...
get_means for Improved Kernel PLS Algorithm #1 will be JIT compiled...
get_stds for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_get_initial_matrices for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_1 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_main_loop_body for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_2 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_3 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_3_body for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_4 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
_step_5 for Improved Kernel PLS Algorithm #1 will be JIT compiled...
stateless_predict for Improved Kernel PLS Algorithm #1 will be JIT compiled...
stateless_fit for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_preprocess_input_matrices for Improved Kernel PLS Algorithm #2 will be JIT compiled...
get_means for Improved Kernel PLS Algorithm #2 will be JIT compiled...
get_stds for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_get_initial_matrices for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_1 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_main_loop_body for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_2 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_3 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_3_body for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_4 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
_step_5 for Improved Kernel PLS Algorithm #2 will be JIT compiled...
stateless_predict for Improved Kernel PLS Algorithm #2 will be JIT compiled...
============================== short test summary info ==============================
FAILED tests/test_ikpls.py::TestClass::test_gradient_pls_1 - AssertionError:
===================== 1 failed, 25 passed in 1403.61s (0:23:23) =====================
</details>

**Comment by parmentelat** [comment]
and oops I forgot to link the meta-issue
https://github.com/openjournals/joss-reviews/issues/6533

**Comment by Sm00thix** [comment]
Hi @parmentelat ,
This appears to be an issue when comparing floats for equality due to the error tolerance being too low. As we have previously discussed, the discrepancy between methods will vary between Python versions and operating system. For the JAX implementations, I suspect they also depend on the hardware (CPU/GPU/TPU).
From your test result I can see that the relative error is about 3^-11 and the absolute error is about 3^-10. Given this rather low value and the fact that the tests pass on my own machine and the 12 different instances in the GitHub action test environment, I think it is safe to assume that the test failing is not due to a bug. As such, I have updated the relative and absolute tolerance for the specific test to be 10^-8. The changes have been committed in https://github.com/Sm00thix/IKPLS/commit/1507921810cb1fa9c073991f1e1c62e707b7eb0f
