### ISSUE TITLE
Support `numpy=2.0.1`?

### ISSUE THREAD

**Issue by ayaanhossain** [Sm00thix/IKPLS#36]
Hello, thank you for maintaining this useful project! Are there any plans to support `numpy=2.0.1` in the near future?

**Comment by Sm00thix** [comment]
Hi @ayaanhossain!
I'm glad you like it 😄

Yes, supporting NumPy 2.0 is something I have wanted to do. I will soon make changes accordingly. I just need to ensure that it does not break any of the other dependencies 😄

**Comment by ayaanhossain** [comment]
Awesome! Glad to hear! Please feel free to close this issue or close it once you've updated the support. I also hope that `ikpls` maintains backwards compatibility with `numpy=1.26` as it does now as well.

**Comment by Sm00thix** [comment]
I will see what I can do to ensure backwards compatibility. I will close this issue once support for NumPy 2.0 is added 😄

**Comment by Sm00thix** [comment]
Closing this as completed since #37 added the functionality :-)
